### PR TITLE
login as defaultaccount with ssh on rs5

### PR DESCRIPTION
**Pull request by paulmon**
@saraclay

### CODE REVIEW

**Comment by jslobodzian** [comment]
Should remove "will" from "To install the client you **will can** search for..."

**Comment by jslobodzian** [comment]
Looks awesome by the way.

**Comment by bfjelds** [comment]
is anything new/different (from the current Docs) needed to use Putty to log into DefaultAccount?

**Comment by saraclay** [comment]
::shipit::

**Comment by paulmon** [comment]
@saraclay Thanks for fixing up the callouts

**Comment by saraclay** [comment]
Ok, we're ready to ::shipit::

**Pull request merged**
