### PR TITLE
Update download links in PrototypeBoards.md

### PR DESCRIPTION
**Pull request by jlaundry**
Previous Raspberry Pi download links were broken

### CODE REVIEW

**Review by rsameser — CHANGES_REQUESTED** [review]
Please remove "en-us" in the new URLs, we do want to localize our links.

**Review by TerryWarwick — COMMENTED** [review]
Thank you for identifying these broken links.  We are going to roll the fix into a separate PR to address a few other issues with this particular page.

**Review by TerryWarwick — CHANGES_REQUESTED** [review]
OK, we rolled your proposed changed into another PR so that we could fix issues with the TOC at the same time.  This PR can be closed out without final submission.  Thanks again!

**Comment by TerryWarwick** [comment]
Change from this PR were rolled into another update that we were making.

**Pull request closed without merging**
